# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('adress', models.CharField(blank=True, max_length=400, null=True, verbose_name='Adress')),
                ('position', models.CharField(blank=True, max_length=400, null=True, verbose_name='ID Number(NIF/NIE)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Adress')),
                ('quantity', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('price', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
