# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supermercado',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Supermercado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
