# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0002_auto_20170212_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
