# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0005_auto_20170212_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Description'),
        ),
    ]
