# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_index', '0006_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Nombre')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('supermercado', models.CharField(blank=True, max_length=400, null=True, verbose_name='Supermercado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Description')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
